// Contest Analytics TypeScript Types
// Mirrors backend Pydantic models for type safety

/**
 * Status of a contest round attempt
 */
export enum RoundStatus {
    COMPLETED = 'completed',
    QUIT = 'quit',
    TIMEOUT = 'timeout',
    STARTED = 'started'
}

/**
 * Records a wrong match attempt for a picture
 */
export interface WrongMatchAttempt {
    matched_with: string;
    timestamp: string; // ISO 8601
}

/**
 * Tracks per-image statistics during gameplay
 */
export interface PictureInteractionMetrics {
    picture_id: string;
    hint_flip_count: number;
    wrong_match_attempts: WrongMatchAttempt[];
    time_to_match_seconds: number | null;
    match_timestamp: string | null; // ISO 8601
}

/**
 * Records a focus loss event
 */
export interface FocusLossEvent {
    timestamp: string; // ISO 8601
    duration_seconds: number | null;
}

/**
 * Records a game pause event
 */
export interface PauseEvent {
    timestamp: string; // ISO 8601
    duration_seconds: number | null;
}

/**
 * Captures user engagement patterns during gameplay
 */
export interface BehavioralMetrics {
    tab_switch_count: number;
    focus_loss_events: FocusLossEvent[];
    pause_events: PauseEvent[];
    visibility_changes: number;
}

/**
 * Device and connection context information
 */
export interface DeviceNetworkInfo {
    platform: string | null;
    browser: string | null;
    app_version: string | null;
    network_type: string | null;
    screen_resolution: string | null;
    viewport_size: string | null;
    user_agent: string | null;
}

/**
 * Records an abnormal timing pattern
 */
export interface AbnormalTimingFlag {
    picture_id: string;
    flag_type: string; // e.g., "too_fast", "too_slow", "impossible_sequence"
    value: number; // The anomalous timing value in seconds
    timestamp: string; // ISO 8601
}

/**
 * Records a sequence of matches faster than human threshold
 */
export interface RapidGuessingPattern {
    picture_ids: string[];
    average_time_seconds: number;
    start_timestamp: string; // ISO 8601
}

/**
 * Integrity and cheat detection metrics
 */
export interface AntiCheatMetrics {
    copy_paste_attempts: number;
    rapid_guessing_patterns: RapidGuessingPattern[];
    repeated_pattern_score: number; // 0-1 scale
    abnormal_timing_flags: AbnormalTimingFlag[];
    keyboard_mouse_ratio: number | null;
    suspicious_activity_score: number; // 0-100 scale
}

/**
 * Main analytics document for a contest attempt
 */
export interface ContestAttemptAnalytics {
    attempt_id?: string; // Generated by backend
    contest_id: string;
    user_id: string;
    language_name: string;
    round_number: number;
    round_status: RoundStatus;
    objects_played: string[];
    picture_interactions: PictureInteractionMetrics[];
    total_time_seconds: number;
    score_achieved: number;
    behavioral_metrics: BehavioralMetrics;
    device_network_info: DeviceNetworkInfo;
    anti_cheat_metrics: AntiCheatMetrics;
    started_at: string; // ISO 8601
    completed_at: string | null; // ISO 8601
    client_timezone: string | null; // e.g., "+05:30"
    session_id: string | null;
}

/**
 * Response from analytics submission
 */
export interface AnalyticsSubmissionResponse {
    success: boolean;
    attempt_id: string;
    message?: string;
}

/**
 * Queued analytics item for retry logic
 */
export interface QueuedAnalytics {
    analytics: ContestAttemptAnalytics;
    timestamp: string;
    retries: number;
}
